name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # This workflow will run when pushing to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        env:
          VITE_FIREBASE_API_KEY: ${{secrets.VITE_FIREBASE_API_KEY}}
          VITE_FIREBASE_APP_ID: ${{secrets.VITE_FIREBASE_APP_ID}}
          VITE_FIREBASE_MEASURE_ID: ${{secrets.VITE_FIREBASE_MEASURE_ID}}
          VITE_FIREBASE_SENDER_ID: ${{secrets.VITE_FIREBASE_SENDER_ID}}
        run: npm run build  # This should build the static files in the 'dist' folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # This is automatically provided by GitHub Actions
          publish_dir: ./dist  # The 'dist' directory where Vite outputs your built site
